apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: oauth/
    repoURL: https://github.com/mabatko/argocd-test
    targetRevision: HEAD
  syncPolicy:
    automated: {}
