apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-seaweed
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: seaweedfs
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    targetRevision: 3.65.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
