apiVersion: v1
data:
  htpasswd: bWFiYXRvOiQyeSQwNSRYc0w1TTk3LzEvU2JJYVY4MUZ4TVZlTlJWYkN0SWUvL1BSNzMwazlnWVN1dXN5TEFmSXE2dQo=
  well: aGVsbG90aGVyZQ==
kind: Secret
metadata:
  name: dxcmcs-users-htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
