apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: dxcmcs_htpasswd_provider3
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: dxcmcs-users-htpasswd-secret
